apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: t1zfbcsie-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/t1zfbcsie-java-quarkus-gitops